# render.yaml (put this in the root of your repo)

services:
  - type: web
    name: nova-flow-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    buildFilter:
      paths:
        - frontend/**/*
    rootDir: frontend
