name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Backend - Install & Test
        run: |
          cd backend
          pip install -r requirements.txt
          pytest
      - name: Frontend - Install & Build
        run: |
          cd frontend
          npm install
          npm run build
